config/routes.rb
Debugging::Application.routes.draw do
  resources :managers

  resources :stores

end

app/models/manager.rb
class Manager < ActiveRecord::Base
  attr_accessible :first_name, :last_name, :salary
end

app/models/store.rb
class Store < ActiveRecord::Base
  belongs_to :manager
  attr_accessible :num_employees, :street_address
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/managers_controller.rb
class ManagersController < ApplicationController
  # GET /managers
  # GET /managers.json
  def index
    @managers = Manager.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @managers }
    end
  end

  # GET /managers/1
  # GET /managers/1.json
  def show
    @manager = Manager.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @manager }
    end
  end

  # GET /managers/new
  # GET /managers/new.json
  def new
    @manager = Manager.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @manager }
    end
  end

  # GET /managers/1/edit
  def edit
    @manager = Manager.find(params[:id])
  end

  # POST /managers
  # POST /managers.json
  def create
    @manager = Manager.new(params[:manager])

    respond_to do |format|
      if @manager.save
        format.html { redirect_to @manager, notice: 'Manager was successfully created.' }
        format.json { render json: @manager, status: :created, location: @manager }
      else
        format.html { render action: "new" }
        format.json { render json: @manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /managers/1
  # PUT /managers/1.json
  def update
    @manager = Manager.find(params[:id])

    respond_to do |format|
      if @manager.update_attributes(params[:manager])
        format.html { redirect_to @manager, notice: 'Manager was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /managers/1
  # DELETE /managers/1.json
  def destroy
    @manager = Manager.find(params[:id])
    @manager.destroy

    respond_to do |format|
      format.html { redirect_to managers_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stores }
    end
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
    @store = Store.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @store }
    end
  end

  # GET /stores/new
  # GET /stores/new.json
  def new
    @store = Store.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @store }
    end
  end

  # GET /stores/1/edit
  def edit
    @store = Store.find(params[:id])
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(params[:store])

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render json: @store, status: :created, location: @store }
      else
        format.html { render action: "new" }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stores/1
  # PUT /stores/1.json
  def update
    @store = Store.find(params[:id])

    respond_to do |format|
      if @store.update_attributes(params[:store])
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store = Store.find(params[:id])
    @store.destroy

    respond_to do |format|
      format.html { redirect_to stores_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Debugging</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/managers/_form.html.erb
<%= form_for(@manager) do |f| %>
  <% if @manager.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@manager.errors.count, "error") %> prohibited this manager from being saved:</h2>

      <ul>
      <% @manager.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :salary %><br />
    <%= f.number_field :salary %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/managers/edit.html.erb
<h1>Editing manager</h1>

<%= render 'form' %>

<%= link_to 'Show', @manager %> |
<%= link_to 'Back', managers_path %>

app/views/managers/index.html.erb
<h1>Listing managers</h1>

<table>
  <tr>
    <th>Last name</th>
    <th>First name</th>
    <th>Salary</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @managers.each do |manager| %>
  <tr>
    <td><%= manager.last_name %></td>
    <td><%= manager.first_name %></td>
    <td><%= manager.salary %></td>
    <td><%= link_to 'Show', manager %></td>
    <td><%= link_to 'Edit', edit_manager_path(manager) %></td>
    <td><%= link_to 'Destroy', manager, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Manager', new_manager_path %>

app/views/managers/new.html.erb
<h1>New manager</h1>

<%= render 'form' %>

<%= link_to 'Back', managers_path %>

app/views/managers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Last name:</b>
  <%= @manager.last_name %>
</p>

<p>
  <b>First name:</b>
  <%= @manager.first_name %>
</p>

<p>
  <b>Salary:</b>
  <%= @manager.salary %>
</p>


<%= link_to 'Edit', edit_manager_path(@manager) %> |
<%= link_to 'Back', managers_path %>

app/views/stores/_form.html.erb
<%= form_for(@store) do |f| %>
  <% if @store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% @store.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :street_address %><br />
    <%= f.text_field :street_address %>
  </div>
  <div class="field">
    <%= f.label :num_employees %><br />
    <%= f.number_field :num_employees %>
  </div>
  <div class="field">
    <%= f.label :manager %><br />
    <%= f.select :manager, Manager.all.select {|m| [m.last_name,m.id]}%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<h1>Editing store</h1>

<%= render 'form' %>

<%= link_to 'Show', @store %> |
<%= link_to 'Back', stores_path %>

app/views/stores/index.html.erb
<div id="header">
<h1>My Store Management System</h1>
</div>
<h1>Listing stores</h1>

<table>
  <tr>
    <th>Street address</th>
    <th>Num employees</th>
    <th>Manager</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @stores.each do |store| %>
  <tr>
    <td><%= store.street_address %></td>
    <td><%= store.num_employees %></td>
    <td><%= store.manager %></td>
    <td><%= link_to 'Show', store %></td>
    <td><%= link_to 'Edit', edit_store_path(store) %></td>
    <td><%= link_to 'Destroy', store, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Store', new_store_path %>

app/views/stores/new.html.erb
<h1>New store</h1>

<%= render 'form' %>

<%= link_to 'Back', stores_path %>

app/views/stores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Street address:</b>
  <%= @store.street_address %>
</p>

<p>
  <b>Num employees:</b>
  <%= @store.num_employees %>
</p>

<p>
  <b>Manager:</b>
  <%= @store.manager %>
</p>


<%= link_to 'Edit', edit_store_path(@store) %> |
<%= link_to 'Back', stores_path %>